version: "3.8"

services:
  db:
    image: postgres:16
    container_name: torn_rw_feed_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: torn
      POSTGRES_PASSWORD: tornpass
      POSTGRES_DB: torn_rw_feed
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
