name: CI

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: torn
          POSTGRES_PASSWORD: tornpass
          POSTGRES_DB: torn_rw_feed
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U torn -d torn_rw_feed"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    env:
      DATABASE_URL: postgresql://torn:tornpass@127.0.0.1:5432/torn_rw_feed

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Install CMake & Ninja
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Configure/Build/Test with run-cmake
        uses: lukka/run-cmake@v10
        with:
            configurePreset: 'ninja-multi'
            buildPreset: 'build-release'
            testPreset: 'test-release'
