name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: torn
          POSTGRES_PASSWORD: tornpass
          POSTGRES_DB: torn_rw_feed
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U torn -d torn_rw_feed"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    env:
      # For waiting with psql
      PGPASSWORD: tornpass
      PGHOST: 127.0.0.1
      PGUSER: torn
      PGDATABASE: torn_rw_feed
      PGPORT: 5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - name: Restore from cache and setup vcpkg executable and data files.
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Wait for PostgreSQL
        run: |
          for i in {1..60}; do
            if psql -c "select 1;" >/dev/null 2>&1; then
              echo "Postgres is ready"
              break
            fi
            echo "Waiting for Postgres..."
            sleep 2
          done
          psql -c "select version();"


      - name: Configure (CMake preset)
        run: cmake --preset ci-ninja

      - name: Build
        run: cmake --build build --config Release -j 2

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
